### ISSUE TITLE
wrong (and duplicated) code sample

### ISSUE THREAD

**Issue by mutzl** [net-daemon/docs#55]
the code snippet in line 51 of https://netdaemon.xyz/docs/api/api_entities doesn't fit the description "select on attributes" and is a duplicate of the sample just above.
So I suppose, it's a copy & paste mistake.
![image](https://user-images.githubusercontent.com/2855185/115486628-57926b00-a257-11eb-8160-a2777ae9c128.png)

**Comment by helto4real** [comment]
yes it is, thanks for reporting.

**Comment by helto4real** [comment]
fixed thanks for reporting
